### ISSUE TITLE
Screen Rotation of Web App on Mobile Device

### ISSUE THREAD

**Issue by snow-swallow** [timelyxyz/blog#13]
1. Use Web API `ScreenOrientation`. But this way's capability is bad, it is only supported on Chrome... 
```JS
  var lockFunction = window.screen.lockOrientation || window.screen.mozLockOrientation || window.screen.msLockOrientation || window.screen.orientation;
  if (lockFunction) {
    lockFunction.lock('landscape');
  } else {
    console.log('Screen lockFunction is not supported');
  }
```

2. Rotate -90deg when screen is portrait mode. But it's not very good when the locale is Arabic... Anyway, this can cover most scenarios. Suggested.
```HTML
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
```
```CSS
@media (max-device-width: $small) and (orientation: portrait) {
  body {
    transform: rotate(-90deg);
    transform-origin: left top;
    width: 100vh;
    overflow-x: hidden;
    position: absolute;
    top: 100%;
    left: 0;
  }
}
```

>Ref
- https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock
- https://css-tricks.com/snippets/css/orientation-lock/
