### ISSUE TITLE
iframe issue on iOS Safari

### ISSUE THREAD

**Issue by snow-swallow** [timelyxyz/blog#17]
>Angular CLI: 1.7.4
Node: 8.10.0
Angular: 5.2.10
OS: darwin x64

**Issue Description**
iframe issues on Safari of iOS 10/11
1. The attribute `height` of iframe does NOT work
2. iframe failed to scroll the content

**Solution**
```HTML
<div class="iframe-wrapper">
  <iframe [src]="xyz.html"></iframe>
</div>
```
```CSS
.iframe-wrapper {
  flex: 1 0 0;
  width: 100%;
  -webkit-overflow-scrolling: touch;
  overflow-y: auto;

  iframe {
    border: 0;
    width: 100%;
    height: 100%;
    display: block;
  }
}
```

>reference
- https://ask.helplib.com/others/post_515317
- http://furybean.com/post/leng-zhi-shi/ios-iframe-height
