### ISSUE TITLE
Customize input/textarea placeholder style

### ISSUE THREAD

**Issue by snow-swallow** [timelyxyz/blog#8]
```CSS
$color: gray;
$fontSize: .875rem;
textarea, input {
	&::-webkit-input-placeholder {
		font-style: italic;
		color: $color;
		font-size: $fontSize;
		line-height: $fontSize;
	}
	&::-moz-placeholder {
		font-style: italic;
		color: $color;
		font-size: $fontSize;
		line-height: $fontSize;
	}
	&::-ms-input-placeholder {
		font-style: italic;
		color: $color;
		font-size: .875rem;
		line-height: $fontSize;
	}
}
```

To be mentioned, pseudo selectors could not be combined into one rule. The following is **incorrect**.
```
&::-webkit-input-placeholder, &::-ms-input-placeholder {
		font-style: italic;
		color: $color;
		font-size: $fontSize;
		line-height: $fontSize;
	}
```

>Ref: 
- https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-input-placeholder
- https://stackoverflow.com/questions/16982449/why-isnt-it-possible-to-combine-vendor-specific-pseudo-elements-classes-into-on
